deploy token, update token, update member added
LimeChain/hedera-eth-bridge-contracts pull request #11
Opened 2021-04-06 17:04 UTC by Holymir

Signed-off-by: Ventsislav Tsochev <ventsi@limechain.tech>

2021-04-06 17:15 UTC, failfmi commented on deployment/setup-scripts/update-member.js
> +const deploy = async (network, secret) => {
Thoughts on running the script via `node update-member.js` instead of `etherlime deploy`?

2021-04-07 08:13 UTC, Daniel-K-Ivanov requested changes

2021-04-07 08:13 UTC, Daniel-K-Ivanov commented on deployment/setup-scripts/testnet-env-deployments.js
> +        updateMember.wait();
I think that we should `await` it otherwise we are not doing anything with this wait

2021-04-07 08:13 UTC, Daniel-K-Ivanov commented on deployment/setup-scripts/testnet-env-deployments.js
> +        sendTransaction.wait();
same here

2021-04-07 08:13 UTC, Daniel-K-Ivanov commented on deployment/setup-scripts/update-token.js
> +    let transaction = await routerInstance.updateWrappedToken(argv.tokenAddress, argv.tokenAddress, argv.tokenStatus);
This shouldn't be working. First argument is `wrappedToken` and the second one is `tokenID` which is in bytes

2021-04-07 08:13 UTC, Daniel-K-Ivanov commented on README.md
> +node ./deployment/setup-scripts/update-member.js --compile false --network /network name or id/ --secret /your private key/ --routerAddress /The address of the deployed router contract/ --memberAddre
I don't think that `--compile` is valid option

2021-04-07 08:13 UTC, Daniel-K-Ivanov commented on README.md
> +node ./deployment/setup-scripts/update-token.js --compile false --network /network name or id/ --secret /your private key/ --routerAddress=/The address of the deployed router/ --tokenAddress=/The add
I don't think that `--compile` is valid option

2021-04-07 08:13 UTC, Daniel-K-Ivanov commented on deployment/setup-scripts/update-token.js
> +}).option("tokenAddress", {
I think that this should be `tokenId`. Token address is term for ethereum based token

2021-04-07 08:13 UTC, Daniel-K-Ivanov commented on README.md
> +#### Update Token Token
remove redundant `Token`

2021-04-07 10:13 UTC, Daniel-K-Ivanov approved these changes

2021-04-07 10:21 UTC, failfmi approved these changes

2021-04-09 07:10 UTC, merged