Feature/contracts v2 no storage wrapped percentage fees
LimeChain/hedera-eth-bridge-contracts pull request #16
Opened 2021-08-09 11:26 UTC by failfmi

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/LimeChain/hedera-evm-bridge-validator/issues/247

**Special notes for your reviewer**:
* Pausing of Wrapped Tokens has not been discussed so far

**Checklist**
- [ ] Documentation added
- [ ] Tests updated

2021-08-09 12:49 UTC, Daniel-K-Ivanov commented on contracts/facets/FeeCalculatorFacet.sol
> +    /// @return The total amount of claimed tokens by the provided validator address
nit: `address _token` inline docs are missing

2021-08-09 12:52 UTC, Daniel-K-Ivanov commented on contracts/facets/FeeCalculatorFacet.sol
> +    function claim(address _token) external override onlyMember {
I don't think that we should have `onlyMember` as modifier. If we remove validator, we still want for him to claim his tokens right?

2021-08-09 12:54 UTC, failfmi commented on contracts/facets/FeeCalculatorFacet.sol
> +    function claim(address _token) external override onlyMember {
Check `GovernanceFacet:updateMember`

2021-08-09 12:59 UTC, Daniel-K-Ivanov commented on contracts/facets/GovernanceFacet.sol
> +            for (uint256 i = 0; i < LibRouter.nativeTokensCount(); i++) {
Can we have an estimate of how much `gas` it costs to execute `LibFeeCalculator.addNewMember();` in order to know when we can expect this to break down due to gas costs..

2021-08-09 13:38 UTC, Daniel-K-Ivanov requested changes
- I think that we must add tests that verify that we can support assets with `0` service fee. I image that there could be assets that will have `0` service fee
- I think that we should have a separate contract called `deployer` that deploys the diamond contract and immediately after that, as part of the same transaction initialises the contract storage with the correct parameters. THis way we will be sure that we will have atomicity between deployment and contract initialisation

2021-08-09 13:38 UTC, Daniel-K-Ivanov commented on contracts/facets/GovernanceFacet.sol
> +                uint256 claimableFees = LibFeeCalculator.claimReward(
Is there a foundamental/technical reason why we are claiming the reward before we remove the member?

2021-08-09 13:38 UTC, Daniel-K-Ivanov commented on contracts/libraries/LibGovernance.sol
> +            );
Is there a fundamental problem of the bridge becoming memberless? (other than not being functional and bridging assets) I suppose that we can always bootstrap members through the contract owner?

2021-08-09 13:38 UTC, Daniel-K-Ivanov commented on contracts/facets/RouterFacet.sol
> +        uint256 _sourceChain,
- Is there a fundamental reason why we need to sign and pass the `sourceChain`?
- Don't we need to sign the current contract address to verify that signatures can be used and are created specifically for this contract?

2021-08-09 13:38 UTC, Daniel-K-Ivanov commented on contracts/libraries/LibGovernance.sol
> +    function validateSignaturesLength(uint256 _n) internal view {
I think that we should be able to configure this property through the multi-sig. Instead of hardcoding 51%, we can make it a configurable property in the storage (in %). My reasoning comes from the fact that here we hardcore 51% but if we run the network with 5/7 sigs we must edit the contract..

2021-08-09 13:38 UTC, Daniel-K-Ivanov commented on contracts/facets/RouterFacet.sol
> +        );
Can we move this logic above the service fee extraction? It seems more appropriate to do the validation immediately after computing the hash

2021-08-09 13:38 UTC, Daniel-K-Ivanov commented on contracts/facets/RouterFacet.sol
> +        uint256 transferAmount = _amount - serviceFee;
I think that we should move this logic after `validateAndStoreTX`. Only after that point, we are sure that every validation passes and we can charge the fees and after that transfer the token

2021-08-09 13:38 UTC, Daniel-K-Ivanov commented on contracts/facets/RouterFacet.sol
> +    function burn(
In order for us to support moving `WHTS` token from Polygon to Ethereum, we can add `targetChain` property. That way users can specify the chain they want to move their tokens to. If they specify `0` it goes to hedera and it unlocks the HTS tokens if they specify `1` it goes to `Ethereum` as `mint` TX

This way we can easily introduce more than bi-directional bridge

2021-08-17 15:29 UTC, Daniel-K-Ivanov commented on contracts/facets/RouterFacet.sol
> +        emit Mint(_wrappedToken, _amount, _receiver);
add `_transactionId` and `_sourceChain` in the events

2021-08-21 09:10 UTC, Daniel-K-Ivanov approved these changes
Excellent work!

2021-08-21 09:10 UTC, Daniel-K-Ivanov commented on test/router.js
> +    it('should revert governance init if percentage is equal to precision', async () => {
Maybe we would want to be able to have 100% threshold. If we end up with 2 validators (unlikely case), I think that we will need to change the threshold to 100%. Or maybe the trust assumptions must be as good as possible and therefore we set it to 100% even if we have 7 validators

2021-08-23 06:25 UTC, Daniel-K-Ivanov approved these changes
LGTM! Lets discuss the outstanding comment and proceed with the merge afterwards

2021-08-23 06:28 UTC, merged