Feature: optimise mint/burn costs
LimeChain/hedera-eth-bridge-contracts pull request #5
Opened 2021-02-24 07:23 UTC by failfmi

**Detailed description**:

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:
* Optimise cost of mint/burn functions

**Checklist**
- [ ] Documentation added
- [x] Tests updated

2021-02-24 09:45 UTC, Daniel-K-Ivanov reviewed
- I think that we should add another parameter to the `Mint` event -> `serviceFee`

2021-02-24 09:46 UTC, Holymir approved these changes

2021-02-24 09:49 UTC, Daniel-K-Ivanov reviewed
The Burn event emits `sender`, `amount` and `receiver`. I think that we should change the event to:
`event Burn(address indexed sender, uint256 amount, uint256 serviceFee, bytes indexed receiver`)

This way, we will have visibility, how much was spend to service fees and how much we should send on the Hedera side. Atm we will simply send the `amount` which is not correct since we won't exclude the service fee.

`amount` could be the "clean" amount to receive after service fee or it could be the initial amount that the user burned, does not matter, important thing is that we need to have the `serviceFee`emitted

2021-02-24 10:08 UTC, Daniel-K-Ivanov requested changes

2021-02-24 10:08 UTC, Daniel-K-Ivanov commented on contracts/Bridge.sol
>      function claim() public {
Let's be cautious here and add `amount` parameter + require `amount <= claimableFees[msg.sender]`

Reasoning:
If for some reason the calculations on how much there is to claim in total (`totalClaimableFees`) and the `claimableFees[msg.sender]` result in discrepancies, we don't want to lock the entire balance of the member. If he has the option to specify amount, he would be able to claim a certain amount and leave only the small discrepancy lost in the contract.

2021-02-24 11:47 UTC, Daniel-K-Ivanov approved these changes

2021-03-01 11:45 UTC, Daniel-K-Ivanov requested changes

2021-03-01 11:45 UTC, Daniel-K-Ivanov commented on test/bridge.js
> +            const aliceTotalClaimableFees = await bridgeInstance.claimableFeesFor(aliceMember.address);
I think that it would be beneficial to test that Alice can claim here fees even though she is not a member now

2021-03-01 14:41 UTC, Daniel-K-Ivanov approved these changes

2021-03-01 14:44 UTC, merged