test-env deployment script
LimeChain/hedera-eth-bridge-contracts pull request #6
Opened 2021-03-02 11:12 UTC by Holymir

- Deploys the WHBAR token and Governance contracts

- Generates 3 member accounts and send them 0.1 ethers

- Sets the required validators to be members of the Governance contract

- Prints out WHBAR, Bridge, Alice, Bob and Carol Wallets

2021-03-02 11:25 UTC, failfmi submitted a review, later dismissed

2021-03-04 09:11 UTC, Daniel-K-Ivanov requested changes

2021-03-04 09:11 UTC, Daniel-K-Ivanov commented on deployment/README.md
> +# Deployment Scripts
I think that it would be better if this is placed in the main readme file

2021-03-04 09:11 UTC, Daniel-K-Ivanov commented on deployment/deploy.js
> +    whbarInstance = await deployer.deploy(WHBAR, {}, "Wrapper HBAR", "WHBAR", 8);
nit: "Wrapped HBAR"

2021-03-04 09:11 UTC, Daniel-K-Ivanov commented on deployment/testnet-env-deployments.js
> +    whbarInstance = await deployer.deploy(WHBAR, {}, "Wrapper HBAR", "WHBAR", 8);
nit: `Wrapped`

2021-03-04 10:03 UTC, Daniel-K-Ivanov submitted a review, later dismissed
Do we even need the `./scripts/hedera-deploy.js` file and the corresponding documentation in the main README.md file? I think not

2021-03-04 12:01 UTC, Daniel-K-Ivanov approved these changes

2021-03-05 07:24 UTC, failfmi approved these changes

2021-03-05 07:25 UTC, merged